language: android

dist: trusty
sudo: enabled

branches:
    only:
        - master

matrix:
    include:
        - os: linux
          dist: trusty
          env: PLATFORM=linux CXX=g++-4.9 CC=gcc-4.9
          addons:
            apt:
              sources: [ 'ubuntu-toolchain-r-test' ]
              packages:
                  - cmake
                  - cmake-data
                  - gcc-4.9
                  - g++-4.9
                  - xorg-dev
                  - libglu1-mesa-dev
                  - libicu-dev
                  - libfreetype6-dev
                  - libharfbuzz-dev
                  - libosmesa-dev
        - os: linux
          env: PLATFORM=android
          addons:
            apt:
              sources: [ 'ubuntu-toolchain-r-test' ]
              packages: [ 'libstdc++6', 's3cmd' ]
          android:
            components: [ 'tools', 'build-tools-25.0.0', 'extra-android-m2repository', 'android-25' ]
          jdk: oraclejdk8

before_install:
    - sudo add-apt-repository -y ppa:kevinkreiser/libsodium
    - sudo add-apt-repository -y ppa:kevinkreiser/libpgm
    - sudo add-apt-repository -y ppa:kevinkreiser/zeromq3
    - sudo add-apt-repository -y ppa:kevinkreiser/czmq
    - sudo apt-get update
    - sudo apt-get install libzmq3-dev libczmq-dev

    - git submodule update --init
    - source ./scripts/travis/before_install.sh

install: ulimit -c

before_script:
    # Set the core file limit to unlimited so a core file is generated upon crash
    - ulimit -c unlimited -S

# build test project
script:
    - source ./scripts/travis/script_build.sh
    - source ./scripts/travis/script_run_tests.sh
    - source ./scripts/travis/script_run_bench.sh

after_success:
    - source ./scripts/travis/script_deploy_android_snapshot.sh
    - source ./scripts/travis/script_deploy_android_demo.sh
